---

- name: "Install Redis on CentOS/RedHat distributions"
  block:
    - name: "Add EPEL repository to Yum"
      yum:
        name: "epel-release"
        state: "present"
        update_cache: true
    - name: "Add package Redis via Yum"
      yum:
        name: "redis"
        state: "present"
        update_cache: true
  when: (ansible_distribution == "CentOS") or (ansible_distribution == "Red Hat Enterprise Linux")

- name: "Install Redis on Debian Family distributions"
  block:
    - name: "Add package Redis via APT"
      apt:
        name: "redis-server"
        state: "present"
        update_cache: true
    - name: disable ipv6 binding (Debian)
      lineinfile:
        path: /etc/redis/redis.conf
        regex: '^bind'
        line: bind 127.0.0.1
  when: (ansible_os_family == "Debian")
  
- name: "Install Redis on Fedora distributions"
  block:
    - name: "Add package redis via DNF"
      dnf:
        name: "redis"
        state: "present"
        update_cache: true
  when: (ansible_distribution == "Fedora")

- name: "Install Redis on Arch Linux family distributions"
  block:
    - name: "Add package redis via Pacman"
      pacman:
        name: "redis"
        state: "present"
        update_cache: true
  when: (ansible_os_family == "Archlinux")

- name: "Install Redis on Suse family distributions"
  block:
    - name: "Add package redis via Zypper"
      zypper:
        name: "redis"
        state: "present"
        update_cache: true
  when: (ansible_os_family == "Suse")
