---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: centos:7
    pre_build_image: true
  - name: centos8
    image: centos:8
    pre_build_image: true
  - name: ubuntu1804
    image: ubuntu:18.04
    pre_build_image: true
  - name: ubuntu1604
    image: ubuntu:16.04
    pre_build_image: true
  - name: ubuntu2004
    image: ubuntu:20.04
    pre_build_image: true
  - name: debian9
    image: debian:9
    pre_build_image: true
  - name: debian10
    image: debian:10
    pre_build_image: true
  - name: fedora31
    image: fedora:31
    pre_build_image: true
  - name: fedora32
    image: fedora:32
    pre_build_image: true
  - name: archlinux
    image: archlinux:20200705
    pre_build_image: true
  - name: opensuseleap15
    image: opensuse/leap:15.2
    pre_build_image: true
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
